### ISSUE TITLE
Flip dosage

### ISSUE THREAD

**Issue by LivUllmann** [suchestoncampbelllab/survivR#18]
Hello!
I am currently running genome-wide survival anallysis using plinkCoxSurv model adjusted for gender and age. The results for some snps have the opposite direction of effect compared to previously published data, that used minor alleles for their HR calculation.   I assume the HR are calculated for A1 allele, which sometimes is a major allele. What does the option flip.dosage do? 

Thank you for your help!

**Comment by oghzzang** [comment]
Oh, it works!!!!
