### ISSUE TITLE
input format for gwasurvivr

### ISSUE THREAD

**Issue by mightyphil2000** [suchestoncampbelllab/survivR#21]
thanks for a great package. My data is in .bgen format. I guess that can't be used as direct input for gwasurvivr? Do you recommend I use plink to export the .bgen files into .vcf format (version 4.3)? There are various export options but do you agree that this is the best option?

**Comment by aarizvi** [comment]
I think there are several options you could use.

1. You could use the bed, bim, and fam files from PLINK - use plinkCoxSurv
2. You can export your bgen file out as a GEN file (which I believe is the same format as IMPUTE2) - use impute2CoxSurv

Unfortunately the VCF files that are being used currently are only from michigan and Sanger imputation servers. You could create a VCF and do this analysis, but you'd likely have to break into the package a little, the feature isn't readily available. Let me know if any other Qs
