### ISSUE TITLE
Error in rowMeans2(genotypes, na.rm = TRUE) :    Argument 'dim.' must be an integer vector of length two.

### ISSUE THREAD

**Issue by shishirdube99** [suchestoncampbelllab/survivR#29]
I am running into this error:

Analyzing part 10811/13838...
Error in rowMeans2(genotypes, na.rm = TRUE) : 
  Argument 'dim.' must be an integer vector of length two.

I even modified the pgen file in plink2 using the following command: --hard-call-threshold 0.4 
where I have adjusted the parameter from 0.2 to 0.49.  Yet I keep running into the same error.  Can you please help?

**Comment by aarizvi** [comment]
Have you tried a larger chunk size?

**Comment by shishirdube99** [comment]
> Have you tried a larger chunk size?

Thanks  - tried that out and it worked!
